### ISSUE TITLE
blacklist file that is too large crash the ultimate antibot

### ISSUE THREAD

**Issue by AkariDream** [Kr1S-D/UltimateAntibotRecoded#10]
my servers are under attack almost every day. until one day it fails. the file is too large to parse.

**Comment by Kr1S-D** [comment]
How many ip are there?

**Comment by AkariDream** [comment]
of course remoed them allows the antibot to function properly. although i dont have that habit(remove blacklist).

**Comment by Kr1S-D** [comment]
I advise you to clean up your blacklist often, as the ip used by the attacks are temporary ip! Also it could also depend on the performance of your server (sorry for the late reply)

**Comment by AkariDream** [comment]
perhaps it is possible to add a regular deletion blacklist. 
i dont restart bungecord very often. 
and also. enabling the plugin after removing the blacklist requires me to wait for a while.

**Comment by Kr1S-D** [comment]
there is a command for clearing the blacklist: `/uab clear blacklist`

**Comment by AkariDream** [comment]
ik this. but a lot of times I don't clean up the blacklist before restarting bungeecord. i couldnt use this command at that time because the plugin is disabled

**Comment by Kr1S-D** [comment]
in that case just remove the file

**Comment by Kr1S-D** [comment]
And, the /uab clear blacklist command will go to clear the blacklist of the ram and when the server restarts the plugin will go to clear the file

**Comment by Kr1S-D** [comment]
> And, the /uab clear blacklist command will go to clear the blacklist in the ram and when the server restarts the plugin will go to clear the file
