### ISSUE TITLE
IPSet & IPTables issue

### ISSUE THREAD

**Issue by AkariDream** [Kr1S-D/UltimateAntibotRecoded#11]
i dont seem to perceive the difference between enabled and not enabled them.
and it seems that only IPSet is working? (i havent used them so idk)

**Comment by Kr1S-D** [comment]
?

**Comment by AkariDream** [comment]
even by blacklist. those IPs can still be added to the server (although uab will still block them in the end)

**Comment by Kr1S-D** [comment]
maybe the firewall is not configured?

**Comment by AkariDream** [comment]
does it need to set anything? i havent used ubuntu much. i think setting it `firewall` to true them will work...

**Comment by Kr1S-D** [comment]
Can u paste what the ugin says at server start?

**Comment by Kr1S-D** [comment]
inactive
