### ISSUE TITLE
[Feature]Peak CPS, Duration ,better type display

### ISSUE THREAD

**Issue by AkariDream** [Kr1S-D/UltimateAntibotRecoded#12]
type is like nantibot and jh antibot. void intent (waiting for connection timeout), join, motd
NONE was replaced by IDLE, i think it would be better.
when there are two or more types. (e.g. Join+Motd) can be changed to join, motd (jh antibot style). and not a combined.
duration placeholder. indicates how long the antibot mode lasts (seconds)
peak cps placeholder. point out that after the antibot mode enabled. maximum of connections

**Comment by Kr1S-D** [comment]
some of these things, have been added in the code, will be added in the new version
