### ISSUE TITLE
It isn't working very well

### ISSUE THREAD

**Issue by Wackgamer** [Kr1S-D/UltimateAntibotRecoded#13]
The plugin isn't stopping all the bots, make a default blacklist YML with a LOT of IP adresses from bots.

**Comment by Kr1S-D** [comment]
Bots change IPs, this means that it is useless to have a default blacklist

**Comment by Kr1S-D** [comment]
Also if you have any kind of problem I invite you to open a ticket on discord!

**Comment by Kr1S-D** [comment]
?
