### ISSUE TITLE
Something about "Strange Player"

### ISSUE THREAD

**Issue by a1375625918** [Kr1S-D/UltimateAntibotRecoded#17]
A player got his IP blocked because of "Strange Player". I'm not sure if this is triggerd by legalname check, since it's hard for me to relate "strange player" to "legal nickname" immediately.

If so then more description is appreciated in game and config comment, plugin homepage etc. "Strange Player Name" can be clear enough to indicate the problem. But the action taken (block IP) may be weird then that a player will receive this even after changing his name to a valid one. Consider one-time kick with rename request and count joins with "strange" names before adding an IP to blacklist.

**Comment by Kr1S-D** [comment]
Are you using Geysers? Strange player exits when a bedrock player connects and you haven't disabled packet check

**Comment by a1375625918** [comment]
No Geyser on server and he is playing Java version.

**Comment by Kr1S-D** [comment]
open a ticket on my discord for the help related this

**Comment by a1375625918** [comment]
I cannot access Discord due to network restrictions. Sorry for that. I cannot reproduce the problem now too.

A simple question here. Is "strange player" a reason for both legalname and slowjoin packet check?

**Comment by Kr1S-D** [comment]
Strange player should be for legalname and packet check

**Comment by a1375625918** [comment]
Thanks for your explanation. I hope it can be documented somewhere appropriate.
