### ISSUE TITLE
The priority of blacklist and whitelist

### ISSUE THREAD

**Issue by a1375625918** [Kr1S-D/UltimateAntibotRecoded#18]
The operator added a blacklisted IP to whitelist. But this IP was still blocked until it's removed from blacklist.

I guess blacklist takes priority so whitelist has no effect when an IP exists in both lists. However, the green **[WHITELIST]** button from `/uab check <id>` in game makes me feel that the blacklisted IP will be allowed simply by executing `/uab whitelist add <IP>` suggested by that green button. Things may become more reasonable if IPs in both lists are finally allowed (give whitelist higher priority), or at least operators should be asked to remove the existing blacklist record when adding IPs to whitelist.

**Comment by Kr1S-D** [comment]
It would be more incoming check for any bot trying to connect so it would slow down the server, when adding an IP to the whitelist it would have to be removed from the blacklist unless there are secondary checks that still blacklist it (VPN, Invalid Name )

**Comment by a1375625918** [comment]
Do you mean that checking whitelist first for every connection will affect performance? Sorry I didn't take it into consideration.

Therefore, just check blacklist when using `/uab whitelist add` . If an operator is trying to add a blacklisted IP to whitelist then, he may receive a tip about removing blacklist records.

**Comment by Kr1S-D** [comment]
ok, it will be added in the next version thanks for the report!

**Comment by Kr1S-D** [comment]
fixed
