### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by mohsinalam91** [Kr1S-D/UltimateAntibotRecoded#2]
These Error are comin
![sdasdas](https://user-images.githubusercontent.com/65994387/180651333-fe7b919b-d845-4528-b503-72b471d9cfc4.PNG)
g

**Comment by Kr1S-D** [comment]
this is a configuration error, did u regen UAB files before upgrade to V4?

**Comment by Kr1S-D** [comment]
@mohsinalam91 are u here?

**Comment by Kr1S-D** [comment]
closed due to inactivity
