### ISSUE TITLE
[Feature] Ping Check

### ISSUE THREAD

**Issue by FallenCrystal** [Kr1S-D/UltimateAntibotRecoded#20]
players must ping the server motd before join the server. this feature should be configurable to be always enable.
btw i would like you to configure three states for each check (always, attack, off). so that the antibot can be configured as appropriate so that the player does not always have to go through unnecessary checks.
> if u can. i hope the check can be adjusted based on the attack. for example, when only join. players only need to ping the server once to pass the check. or when the bot doesnt look like its trying to reconnect. players can reconnect to join the server.
when attacked by bots that contain blacklisted names (e.g. "mcstorm"). players dont even need to pass any checks.
if u made these. it would be amazing. even better than any other antibot ive ever seen.

**Comment by Kr1S-D** [comment]
the ping check is asked only during attack, the first join check can be disabled

**Comment by AkariDream** [comment]
> the ping check is asked only during attack, the first join check can be disabled

no. this looks more like a feature request. its just that most of the time it is not necessary to pass such a complex check.
