### ISSUE TITLE
[Feature] Waterfall logger improve.

### ISSUE THREAD

**Issue by FallenCrystal** [Kr1S-D/UltimateAntibotRecoded#24]
waterfall provides its own log4j logger.
some plugins will compete for bungeecord's logger filter. this results in all their plugins having only one plugin's logger filter valid.

so if u can. u can use `io.github.waterfallmc.waterfall.log4j.WaterfallLogger` to create and set up a filter instance.
[here](https://github.com/Kr1S-D/UltimateAntibotRecoded/blob/master/UltimateAntibot-bungeecord/src/main/java/me/kr1s_d/ultimateantibot/UltimateAntiBotBungeeCord.java#L103)
if u r concerned about the compatibility of the original bungeecord. u can enter the path in its entirety into the method. if catch `NoClassDefFoundError`. the original bungeecord logger filter instance will be set.

**Comment by Kr1S-D** [comment]
Hi I saw your pull request, I will manually add the new filter type like you did, however I'm not sure if it works totally on other forks so I have to check and lately I don't have much time available, as soon as I can I will implement if possible the new filter! Thanks again for the pull request!

**Comment by FallenCrystal** [comment]
it does work with any bungeecord fork. ive tried bungeecord and waterfall(and other fork, flamecord, etc). there are no problems. the only caveat is not to import but to use the full package name. otherwise, an error will be thrown directly in case of incompatibility.

**Comment by Kr1S-D** [comment]
Given waterfall's decision not to continue development I don't think it would be useful to add an API that won't be updated, thanks anyway for everything you've done
