### ISSUE TITLE
[Bug] LuckPerms filterts not working on spigot

### ISSUE THREAD

**Issue by f3f5-dev** [Kr1S-D/UltimateAntibotRecoded#26]
[LuckPerms] Another plugin has cancelled the connection for
i have enabled, checked message in config.yml

**Comment by f3f5-dev** [comment]
@Kr1S-D pls hotfix this, i see and see spam
 
![Screenshot_1](https://github.com/Kr1S-D/UltimateAntibotRecoded/assets/137526883/dbb9e69f-5c79-4c86-9f2c-f62cdd5bebe9)

**Comment by f3f5-dev** [comment]
#Custom message console filter (works 24h/7)
persistent-filter: 
  - "Another plugin has cancelled the connection for" #luckperms on spigot
  - "Internal Exception: io.netty.handler.codec.DecoderException: The received string length is longer than maximum allowed"


it works , but atack-filter not.
also with atack uab says 'foffline' not normal?

**Comment by f3f5-dev** [comment]
![Screenshot_1](https://github.com/Kr1S-D/UltimateAntibotRecoded/assets/137526883/6173cff8-1348-4978-afa0-eeca79e029ca)

**Comment by FallenCrystal** [comment]
> it works , but atack-filter not

only one console filter can be registered. please check ur other plugins.

**Comment by f3f5-dev** [comment]
> > it works , but atack-filter not
> 
> only one console filter can be registered. please check ur other plugins. (duplicated ur issue #28)

not a other plugin issues
tested paper 1.12.2 uab luckperms

**Comment by FallenCrystal** [comment]
> not a other plugin issues

all right. my fault. he used log4j in the code in the spigot version. but the log4j he used is outdated.

and also. i dont recommend installing antibot on spigot. preferably on bungeecord or velocity.

**Comment by Kr1S-D** [comment]
> > not a other plugin issues
> 
> all right. my fault. he used log4j in the code in the spigot version. but the log4j he used is outdated.
> 
> and also. i dont recommend installing antibot on spigot. preferably on bungeecord or velocity.

i updated lib in the new update but idk if is fixed or not
