### ISSUE TITLE
colour

### ISSUE THREAD

**Issue by 1zyao** [Kr1S-D/UltimateAntibotRecoded#3]
![image](https://user-images.githubusercontent.com/107829654/182004559-c83cc1c2-0053-403a-9b5a-df37062cd7ae.png)
There is no color on paper1.19, but a bunch of color codes, which do not appear in bungeecord
![image](https://user-images.githubusercontent.com/107829654/182004618-cb59e2d6-f36c-44e8-9fcb-4af2b44f1f63.png)

**Comment by 1zyao** [comment]
This may be my problem

**Comment by Kr1S-D** [comment]
Hello this issue has been fixed in version V4.04!
