### ISSUE TITLE
You are not a player

### ISSUE THREAD

**Issue by pixkk** [Kr1S-D/UltimateAntibotRecoded#30]
Greetings. I would like to ask about adding a user verification function directly from the console. 

It is not always possible to enter the server, and when a player asks to check the problem for a given ID, I can’t just see the IP address to add it to the whitelist.

/uab check <id> return "You are not a player".

**Comment by FallenCrystal** [comment]
it really doesnt work with consoles. 
it uses `BaseComponent` with `text:hover`. it cannot be print in the console. 
perhaps there can have another way to add some code directly to the `backlist remove` command to auto parse the blacklist profile and remove it in blacklist i think.

**Comment by pixkk** [comment]
> perhaps there can have another way to add some code directly to the backlist remove command to auto parse the blacklist profile and remove it in blacklist i think.

Yes it would be nice.

**Comment by Kr1S-D** [comment]
> 
can you explain better?

**Comment by pixkk** [comment]
> > 
> 
> can you explain better?

I thought I painted it in such detail. I want to be able to analyze incidents through the console. That is, to see the blocked IP address, the reason for blocking directly in the console.

**Comment by Kr1S-D** [comment]
you can check blacklisted ips in the blacklist file after an attack or after server restart

**Comment by pixkk** [comment]
After attack file banlist not updating. Restart server - it's problem, when server has more than 50 people.
