### ISSUE TITLE
Too many nicks from 172.18.0.1

### ISSUE THREAD

**Issue by pixkk** [Kr1S-D/UltimateAntibotRecoded#31]
Hello. I'm use UAB on bungeecord. Server working on pterodactyl.io, which use docker with local address 172.18.0.1.

When some users run mcstorm from personal computer, Bots enter the server as ordinary players (that is, under the internal address of the docker). As a result, the antibot blocks this address and no one else can enter the server.

**Comment by FallenCrystal** [comment]
why does it come in to an address like that? ask your hosting provider. 
uab uses bungeecord's interface to get addresses and doesnt modify anything in the network.
if uab recognition is incorrect. it will also prove that bungeecord recognizes an incorrect address.
if ur host uses haproxy to relay your connection. try to set 'proxy_protocol' to 'true' and try again.

**Comment by pixkk** [comment]
The bangicord server is located in a docker container which has a local ip address of 172.18.0.1. Does this count as a proxy protocol?

**Comment by FallenCrystal** [comment]
**ask your host staff/administrator**. and it stands to reason that docker should also relay addresses for remote connections.

**Comment by pixkk** [comment]
I don't have an administrator. I personally rent a server. And if I had an admin, he would send me here, since the problem occurs in the plugin.

I am writing again - NOT all users get to the 172.18.0.1 address.

**Comment by FallenCrystal** [comment]
do u mean "not all users access the server as the **172.18.0.1 address**"?
if yes. u should open the issue in the repository of bungeecord or waterfall (depending on the fork you use). and not here.
