### ISSUE TITLE
Can a new feature be added

### ISSUE THREAD

**Issue by Thexiaoyuqaq** [Kr1S-D/UltimateAntibotRecoded#32]
Administrators can turn off their own reminders
I found on my server that
The offline of the actionbar has been continuously displayed, affecting the plugin content of many servers
Furthermore, you can add a command to switch the AntiBot state

**Comment by FallenCrystal** [comment]
~~说的很好 下次别直接拿翻译器的句子拉出来用了~~

所以如果我没理解错的话 你想列出以下问题? 如果有其它问题或者描述 另再补充
 - 状态栏总是在被攻击时显示 但你有其它插件需要在状态栏中显示内容
     - 这可以通过将权限 `uab.notifications.automatic`(似乎是的) 设为false来解决
  - 切换反击确认状态
     - 我真的不觉得手动干涉反机器人的状态是好事 且它们大部分都是硬编码(被提前设计好的)
     - 按理来讲这种东西应该工作的很好 如果真的有什么东西不按预期行为工作 你应该打开一个issue

还有一些注意的事:
  - 最好针对于你的问题打开多个issue 或尝试将issue整理成list. 好吧 ——将多个问题或建议塞在一个issue(除非它们相关)是一个非常愚蠢的行为 它们最终将会导致你的comment混乱(至少对于整理成list来讲 打开多个issue可以减少很多事情)
  - 不要打开标题内容为 `新功能` `插件不工作` `Bugs` 这样毫无意义的标题 这非常容易让别人忽视你的问题
     - 正确的例子应该是像 `[Feature] Add ability to switch antibot state` `[Bug] Plugin's xxx not working` 
  - 虽然我知道在这里说这个不是好的 但我仍然建议:
     - 不要使用mcbbs上的任何推荐的反机器人 我更愿意称呼它为 `挨打时自动开启白名单`. `AntiAttackRL`和`AntiFakePlayerBC`也是如此. 但它们的性能确实比uab更低. 如果你不是在找挨打时自动开白名单的反机器人插件. 去别处找找 或者我可以给你一些建议. 也不要在水龙头等后端服务端上运行反机器人 ——如果你有能力搭建一个Velocity或BungeeCord代理.

**Comment by Kr1S-D** [comment]
write in english please...

**Comment by Thexiaoyuqaq** [comment]
> write in english please...

这是国外的人的插件 不是每个人都像你一样看的懂中文，你要不给我翻译个其他国家语言？ 如果这个插件是中国人的插件我会使用中文，但我的能力可不像你，我需要借助工具，不要会个英语就随便说别人，国外人看不懂中文懂？，国外的插件用英文ok?

**Comment by Thexiaoyuqaq** [comment]
> ~说的很好 下次别直接拿翻译器的句子拉出来用了~
> 
> 所以如果我没理解错的话 你想列出以下问题? 如果有其它问题或者描述 另再补充
> 
> * 状态栏总是在被攻击时显示 但你有其它插件需要在状态栏中显示内容
>   
>   * 这可以通过将权限 `uab.notifications.automatic`(似乎是的) 设为false来解决
> * 切换反机器人状态
>   
>   * 我真的不觉得手动干涉反机器人的状态是好事 且它们大部分都是硬编码(被提前设计好的)
>   * 按理来讲这种东西应该工作的很好 如果真的有什么东西不按预期行为工作 你应该打开一个issue
> 
> 还有一些注意的事:
> 
> * 最好针对于你的问题打开多个issue 或尝试将issue整理成list. 好吧 ——将多个问题或建议塞在一个issue(除非它们相关)是一个非常愚蠢的行为 它们最终将会导致你的comment混乱(至少对于塞一起来讲 打开多个issue或整理成list可以减少很多事情)
> * 不要打开标题内容为 `新功能` `插件不工作` `Bugs` 这样毫无意义的标题 这非常容易让别人忽视你的问题
>   
>   * 正确的例子应该是像 `[Feature] Add ability to switch antibot state` `[Bug] xxx not working`
> * 虽然我知道在这里说这个不是好的 但我仍然建议:
>   
>   * 不要使用mcbbs上的任何推荐的反机器人 我更愿意称呼它为 `挨打时自动开启白名单`. `AntiAttackRL`和`AntiFakePlayerBC`也是如此. 但它们的性能确实比uab更低. 如果你不是在找挨打时自动开白名单的反机器人插件. 去别处看看, 如果实在找不到, 我也可以给你一些建议.
>   * 如果你只是在运行跟自己朋友一起玩的小服却遇到了恶意攻击 确实可以使用挨打自动开白名单插件.. 但如果你正在计划或现在就在运营某个中小型甚至大型network 则不要使用此类白名单插件. 至少攻击者可以达到它们的目的: 拒绝服务
>   * 不要在水龙头等后端服务端上运行反机器人 ——如果你有能力搭建一个Velocity或BungeeCord代理.
> 
> > 一堆错字我真的麻了 要是有啥错字的话 凑合看下吧
1.对于开头的"说的很好 下次别直接拿翻译器的句子拉出来用了",我的英语没有那么厉害我需要借助工具谢谢,理解下
2.">   * 我真的不觉得手动干涉反机器人的状态是好事 且它们大部分都是硬编码(被提前设计好的)
>   * 按理来讲这种东西应该工作的很好 如果真的有什么东西不按预期行为工作 你应该打开一个issue"
在我使用的时候，当压测结束后，boss栏会显示 等待压测...，不会结束而是反复在等待，否则我也不会来这里开一个issue

3. “>   * 如果你只是在运行跟自己朋友一起玩的小服却遇到了恶意攻击 确实可以使用挨打自动开白名单插件.. 但如果你正在计划或现在就在运营某个中小型甚至大型network 则不要使用此类白名单插件. 至少攻击者可以达到它们的目的: 拒绝服务
>   * 不要在水龙头等后端服务端上运行反机器人 ——如果你有能力搭建一个Velocity或BungeeCord代理.”
就因为我是Bungeecord大型群组服务器，我才需要这种插件


而且没人规定必须要这么规范，如果我不这样，会被封禁？不要这样说一个新人，我只是通过作者在Spigotmc的帖子找到这里的，不要把任何人都看成和你一样的

**Comment by Thexiaoyuqaq** [comment]
> ~说的很好 下次别直接拿翻译器的句子拉出来用了~
> 
> 所以如果我没理解错的话 你想列出以下问题? 如果有其它问题或者描述 另再补充
> 
> * 状态栏总是在被攻击时显示 但你有其它插件需要在状态栏中显示内容
>   
>   * 这可以通过将权限 `uab.notifications.automatic`(似乎是的) 设为false来解决
> * 切换反机器人状态
>   
>   * 我真的不觉得手动干涉反机器人的状态是好事 且它们大部分都是硬编码(被提前设计好的)
>   * 按理来讲这种东西应该工作的很好 如果真的有什么东西不按预期行为工作 你应该打开一个issue
> 
> 还有一些注意的事:
> 
> * 最好针对于你的问题打开多个issue 或尝试将issue整理成list. 好吧 ——将多个问题或建议塞在一个issue(除非它们相关)是一个非常愚蠢的行为 它们最终将会导致你的comment混乱(至少对于塞一起来讲 打开多个issue或整理成list可以减少很多事情)
> * 不要打开标题内容为 `新功能` `插件不工作` `Bugs` 这样毫无意义的标题 这非常容易让别人忽视你的问题
>   
>   * 正确的例子应该是像 `[Feature] Add ability to switch antibot state` `[Bug] xxx not working`
> * 虽然我知道在这里说这个不是好的 但我仍然建议:
>   
>   * 不要使用mcbbs上的任何推荐的反机器人 我更愿意称呼它为 `挨打时自动开启白名单`. `AntiAttackRL`和`AntiFakePlayerBC`也是如此. 但它们的性能确实比uab更低. 如果你不是在找挨打时自动开白名单的反机器人插件. 去别处看看, 如果实在找不到, 我也可以给你一些建议.
>   * 如果你只是在运行跟自己朋友一起玩的小服却遇到了恶意攻击 确实可以使用挨打自动开白名单插件.. 但如果你正在计划或现在就在运营某个中小型甚至大型network 则不要使用此类白名单插件. 至少攻击者可以达到它们的目的: 拒绝服务
>   * 不要在水龙头等后端服务端上运行反机器人 ——如果你有能力搭建一个Velocity或BungeeCord代理.
> 
> > 一堆错字我真的麻了 要是有啥错字的话 凑合看下吧

这个插件可以选择关闭 "断开玩家连接" 我喜欢他的自动拉黑名单功能

**Comment by FallenCrystal** [comment]
> 而且没人规定必须要这么规范，如果我不这样，会被封禁？不要这样说一个新人，我只是通过作者在Spigotmc的帖子找到这里的，不要把任何人都看成和你一样的

并不是 "任何人都和我一样". 我只是在告诉你如何做是**比较好的**. 我只是在告诉你有更好的选择 如果你喜欢这个插件 我也不会说什么.

还有 说话味挺冲的.. `如果我不这样 会被封禁?` `不要把任何人都看成和你一样的`. 整的我好像在跟你吵架似的。。

> 这个插件可以选择关闭 "断开玩家连接" 我喜欢他的自动拉黑名单功能

几乎任何反机器人插件(是的..再次排除部分白名单插件)都会针对机器人有自动拉黑名单的功能. 

> 对于 "自动白名单插件" ?

uab不一定一直保持lockdown. 但如果它无法访问api验证代理 ——那么是的 它将激活白名单 而且对于慢速自动重连机器人来说 它不可能拦截所有代理 所以对此没什么抵抗力 如果你正在遭遇一些稍微愚蠢一些的机器人且你的所有玩家都被列入了黑名单 那么确实对你来说很好

在我的角度这里自动白名单达成的拒绝服务指的是: 当你打开白名单时 就针对新玩家已经达成了"拒绝服务"的目的

**Comment by Thexiaoyuqaq** [comment]
小雨已收到你的来信已存放至小雨的收件箱
