### ISSUE TITLE
some actionbar not works 

### ISSUE THREAD

**Issue by f3f5-dev** [Kr1S-D/UltimateAntibotRecoded#36]
antibot: "%prefix%&cBot&7/&cPing &f%bots%&7/&f%pings% &4- &cBlacklist&7/&cQueue&7/&cWhitelist &f%blacklist%&7/&f%queue%&7/&f%whitelist% &4- &cVerify &f%underverification% » &c&l%type%"
  packets: "%prefix%&cPackets &f%packets%/sec &4- &cBlocked &f%totalpackets% &4- &cVerify &f%underverification% » &c&l%type%"

when atack, its still "OFFLINE" bossbar

**Comment by f3f5-dev** [comment]
ver spigot

**Comment by Kr1S-D** [comment]
Only on spigot? Can u test bungeecord?

**Comment by f3f5-dev** [comment]
i cant test because right now i dont have any bot attack service
