### ISSUE TITLE
console filters (uab 4.0.8) spigot

### ISSUE THREAD

**Issue by f3f5-dev** [Kr1S-D/UltimateAntibotRecoded#37]
![Screenshot_1](https://github.com/Kr1S-D/UltimateAntibotRecoded/assets/137526883/c51f7621-3ed5-4354-bce5-955c9a47c5c4)

**Comment by Kr1S-D** [comment]
Can u send me the config.yml thath you are using on pastebin?

**Comment by f3f5-dev** [comment]
false report, in last ver it fixed

**Comment by f3f5-dev** [comment]
@Kr1S-D reopen this in in logs: 
![image](https://github.com/Kr1S-D/UltimateAntibotRecoded/assets/137526883/078de585-afae-4076-91af-141fb18fcc7a)

config: 




attack-filter:
  - "Another plugin has cancelled the connection for" #luckperms on spigot
  - "The UUID the player is connecting with now is NOT Mojang-assigned" #luckperms on bungeecord

#Custom message console filter (works 24h/7)
persistent-filter: 
  - "Another plugin has cancelled the connection for"
