### ISSUE TITLE
strange name in /uab help & stats 

### ISSUE THREAD

**Issue by ghost** [Kr1S-D/UltimateAntibotRecoded#38]
![Screenshot_2](https://github.com/Kr1S-D/UltimateAntibotRecoded/assets/137526883/92e8f183-03d9-4449-a90d-ebca37dcca36)
running ultimateultimate?

**Comment by Kr1S-D** [comment]
What is the command that you do before getting this error?

**Comment by f3f5-dev** [comment]
for example /uab help

**Comment by f3f5-dev** [comment]
caused only in the console

**Comment by f3f5-dev** [comment]
i tested two hostings and same result

**Comment by Kr1S-D** [comment]
only bukkit version?

**Comment by f3f5-dev** [comment]
yes
