### ISSUE TITLE
Velocity does not support 3.3.0

### ISSUE THREAD

**Issue by sekaom** [Kr1S-D/UltimateAntibotRecoded#40]
At velocity 3.2.x, the main defenses of the velocity version of the plugin work fine.  
After upgrading to 3.3.x, the plugin doesn't seem to detect the start of an attack, and is in a very weak defense situation, only doing a clear out of the dummies that have already been in  
All statuses show that the attack has not started  
This was in earlier 3.3.x  
Nowadays it doesn't work on Velocity anymore, with this error at startup [log](https://katb.in/abegekatiso)  
I was running Velocity 3.3.0-SNAPSHOT (git-b9b11665-b343) when I sent this issue.

**Comment by Kr1S-D** [comment]
can u test with the last velocity version on my discord server and open a ticket reporting the error?
