### ISSUE TITLE
About the API key of proxycheck.io

### ISSUE THREAD

**Issue by TianmuTNT** [Kr1S-D/UltimateAntibotRecoded#41]
Actually, it is possible to register multiple proxycheck.io API keys, so please add the feature of using multiple API keys!

**Comment by TianmuTNT** [comment]
If you are willing, please make sure to add it. Thank you very much

**Comment by TianmuTNT** [comment]
Uh, by the way, my English is not good, so I am using translation software. If you don't understand what I am saying, I'm sorry

**Comment by PukPukov** [comment]
The IP from which you are making requests will be the same so they could easily ban you for that.

**Comment by PukPukov** [comment]
Also this is just uncivilized having server with online so big that it exceedes quota of 1k requests per day and still stealing from developers.

**Comment by Kr1S-D** [comment]
I don't see any API documentation that allows you to do this officially, incorrect use of the API for proxycheck is not something I intend to do, sorry.
