### ISSUE TITLE
Vírus Detected ?

### ISSUE THREAD

**Issue by comonier** [Kr1S-D/UltimateAntibotRecoded#7]
Just updating bungeecord and check there was a update from UAB to download
![image](https://user-images.githubusercontent.com/19571541/186780766-7db1bf7d-d355-47e0-985d-fdfafd7a156d.png)

So.... after download, Windows sayed it have vírus!
![image](https://user-images.githubusercontent.com/19571541/186780543-3040676d-ca4b-46c8-baf2-3591cf9e9b4d.png)

from: `https://github.com/Kr1S-D/UltimateAntibotRecoded/releases/tag/V4.0.5`

No other vírus on all plugins i had downloaded  That was the first time i saw that.

**Comment by Kr1S-D** [comment]
Hello, first of all I can guarantee you that there are no viruses, since the plugin is open source so the presence of any malicious code can be reported by viewing the code itself.

Probably the problem was that the plugin contains many libraries. For the rest do not worry! : D
