### ISSUE TITLE
Problems with Chinese names

### ISSUE THREAD

**Issue by yyhhkya** [Kr1S-D/UltimateAntibotRecoded#8]
edition：UltimateAntibot-spigot-4.0.5
Players with Chinese names will be automatically blacklisted by the plug-in when they enter the server
![image](https://user-images.githubusercontent.com/87574541/193177159-e822bee4-a450-47f9-b321-260168864748.png)

**Comment by Kr1S-D** [comment]
Go in the config.yml and disable the invalid-name check

**Comment by Kr1S-D** [comment]
Does the problem has been solved?

**Comment by yyhhkya** [comment]
I have tried to back up the server before and it seems that I haven't found this problem. I don't know why this happens to the latest server

**Comment by yyhhkya** [comment]
I have tried to back up the server before and it seems that I haven't found this problem. I don't know why this happens to the latest server

**Comment by yyhhkya** [comment]
Now the problem arises again

**Comment by Kr1S-D** [comment]
Can you open a ticket on discord?

**Comment by Kr1S-D** [comment]
?

**Comment by yyhhkya** [comment]
what?

**Comment by yyhhkya** [comment]
What is "ticket on discord"

**Comment by Kr1S-D** [comment]
A private support when you can share provat datas to be helped

**Comment by yyhhkya** [comment]
How to share

**Comment by Kr1S-D** [comment]
Do you have discord?

**Comment by Kr1S-D** [comment]
?

**Comment by yyhhkya** [comment]
is “https://discord.com/”?

**Comment by yyhhkya** [comment]
I have this

**Comment by Kr1S-D** [comment]
Yes

**Comment by Kr1S-D** [comment]
U need to create an account and join my server, in this way i can help you with the plugin as best i can

**Comment by yyhhkya** [comment]
Can you give me an invitation link to the server?

**Comment by Kr1S-D** [comment]
You can take it by clicking on discord butto in the spigot plugin page

**Comment by yyhhkya** [comment]
ok

**Comment by yyhhkya** [comment]
What should I do in discord?

**Comment by Kr1S-D** [comment]
problem solved on discord
